#!/usr/bin/env python
import sys

"""Just a helper script to provide a shorter name for the actual usage of this
application.
"""
from theme_boost_union_test_envs import app
from theme_boost_union_test_envs.app import UserInterface

if __name__ == "__main__":
    sys.exit(app.main(UserInterface.CLI))
