core:
  working_dir: "./example_pwd"
  moodle:
    cache:
      # relative to core.working_dir
      dir: ".moodles/"
repos:
  boost_union:
    url: "https://github.com/moodle-an-hochschulen/moodle-theme_boost_union"
    # don't edit; relative to the test infrastructure dir
    dir: "theme/boost_union"
  moodle_docker:
    url: "https://github.com/moodlehq/moodle-docker"
    # don't edit; relative to the core.working_dir
    dir: ".moodle-docker"
adapters:
  moodle:
    downloader:
      url: "https://github.com/moodle/moodle/archive/refs/tags/"
      retries: 5
      retry_timeout: 15
