# if not used for local testing: change to correct environment
environment: "env.local.yml"
repos:
  moodle_docker:
    url: "https://github.com/eloquenza/moodle-docker"
adapters:
  moodle:
    downloader:
      url: "https://github.com/moodle/moodle/archive/refs/tags/"
      retries: 5
      retry_timeout: 15
